modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "GNU GPL 3.0"

[[mods]]
modId = "optionsprofiles"
version = "${version}"
displayName = "Options Profiles"
authors = "AxolotlMaid"
description = '''
Load and save your options from in-game.
'''
logoFile = "icon.png"

[[dependencies.optionsprofiles]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.optionsprofiles]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.optionsprofiles]]
modId = "architectury"
mandatory = true
versionRange = "[4.11.93,)"
ordering = "AFTER"
side = "BOTH"
